# https://code.visualstudio.com/api/working-with-extensions/continuous-integration#travis-ci
language: node_js
os: [linux]
node_js: 14

# https://github.com/microsoft/vscode/issues/33998
addons:
  apt:
    packages:
      - libsecret-1-dev

install:
  - |
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - yarn
  - yarn lint

cache: yarn
